export default {
    uz: {
        som: ' so\'m',
        search: 'Kategoriya',
        admin:'Admin',
        til:'Tilni o\'zgartirish',
        boglan: 'Ulanish',
        sot: 'Sotib oling!',
        qosh: 'Savatga qo\'shish',
        sifat: 'Tavsif va xususiyatlar',
        karzinka: 'Savat',
        bosh: 'Savat bo\'sh',
        lekin: 'Lekin buni tuzatish uchun hech qachon kech emas :)',
        mahsulot: 'Mahsulotlar katalogiga',
        jami: 'JAMI',
        otish: 'To\'lovga o\'ting',
        tanlanganar: 'Tanlanganlar bo\'sh',
        zakaz: 'Buyurtma',
        dastavka: 'Kuryer yetkazib berish',
        locat: 'Yetkazib berish manzili',
        tuman: 'Ko\'cha / tuman',
        uy: 'Shahar',
        padez: 'Uy',
        kvartira: 'Kvartira raqami',
        vash: 'Sizning buyurtmangiz',
        tolov: 'To\'lov usuli',
        tg:'Telegram orqali tolov qilish',
        insta: 'Instagram oqali tolov qilish',
        qabul:'Qabul qiluvchining raqami',
        berish: 'Buyurtma berish!',
        token:'Buyurtma raqamingiz No 123123, menejerimiz siz bilan bog\'lanadi. Iltimos telefoningiz yoniq tursin!!! '


    },
    ru: {
        som: 'рубл',
        search: 'Категория',
        admin:'Админ',
        til:'Изменить язык',
        boglan: 'Связь',
        sot: 'Купить!',
        qosh: 'Добавить в корзину',
        sifat: 'Описание и характеристики',
        karzinka: 'Корзина',
        bosh: 'Корзина пуста',
        lekin: 'Но это никогда не поздно исправить :)',
        mahsulot: 'В каталог товаров',
        jami: 'ИТОГО',
        otish: 'Перейти к оформлению',
        tanlanganar: 'Выборы пусты',
        zakaz: 'Оформление заказа',
        dastavka: 'Доставка курьером',
        locat: 'Адрес доставки',
        tuman: 'Улица / Район',
        uy: 'Город',
        padez: 'Дом',
        kvartira: 'Квартира',
        vash: 'Ваш заказ',
        tolov: 'Способ оплаты',
        tg:'Оплата через Телеграм',
        insta: 'Оплата аккаунта инстаграм',
        qabul:'Номер Получателя',
        berish:'Разместите заказ!',
        token:'Номер вашего заказа 123123, наш менеджер свяжется с вами. Пожалуйста, не выключайте телефон!!!'

    },
    en: {
        som: '$',
        search: 'Category',
        admin:'Admin',
        til:'Change the language',
        boglan: 'Connection',
        sot: 'Buy it!',
        qosh: 'Add to Basket',
        sifat: 'Description and characteristics',
        karzinka: 'Basket',
        bosh: 'Basket empty',
        lekin: 'But it\'s never too late to fix it :)',
        mahsulot: 'To product catalog',
        jami: 'TOTAL',
        otish: 'Go to checkout',
        tanlanganar: 'The selections are empty',
        zakaz: 'Checkout',
        dastavka: 'Courier delivery',
        locat: 'Delivery address',
        tuman: 'Street / Area',
        uy: 'City',
        padez: 'House',
        kvartira: 'Apartment',
        vash: 'Your order',
        tolov: 'Payment method',
        tg:'Payment via Telegram',
        insta: 'Instagram account payment',
        qabul:'Recipient number',
        berish: 'Place an order!',
        token:'Your order number is 123123, our manager will contact you. Please keep your phone on!!!'
        
        

    },
}